# Generated by Django 4.2.7 on 2023-11-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_friends_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends_count',
            field=models.IntegerField(default=0),
        ),
    ]
